name: Feature Request
description: Suggest an idea for the project.
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to open a feature request! Before you fill out this form, please search the issues page for any similar requests. If you find some that are similar but not exactly the same, feel free to link them.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Desired Solution
      description: Provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Are there any other ways this problem could be solved? Describe other solutions or features you've considered here.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Is there any other context you want to share about your feature request?
